trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path

from . import views

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('stocks/', views.apicall, name="stock"),
    path('add', views.apicall, name='add'),
    path('stock_details/<int:position_id>/', views.stock_details, name='stock_details'),
]

trash_collector/positions/urls.py
from django.urls import path

from . import views

app_name = 'positions'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.create, name='add_stock'),
    path('update_all/', views.update_all, name='update_all'),
    path('edit/<int:position_id>/', views.edit, name='edit')

]

trash_collector/templates/base.html
<!DOCTYPE html>
<html>
<head>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
{% block scripts %}
{% endblock scripts %}
  <div style="background-image: linear-gradient(to right top, #ffffff, #eeedfa, #dadcf5, #c5cbf1, #acbced, #9bbdf2, #85bef6, #69bff8, #52cffe, #41dfff, #46eefa, #5ffbf1);">
{% if user.is_authenticated %}
  {% for group in user.groups.all%}
    {% if group.name == "Customers" %}
       <p><nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Philip Stock Tracker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{% url 'customers:index'%}">Home</a>
        <a class="nav-link" href="{% url 'positions:index'%}">Add a New Stock</a>
         <a class="nav-link" href="{% url 'logout'%}">Logout</a>
        </p>
      </div>
    </div>
  </div>
</nav></p>
    {% elif group.name == "Employees" %}
       <p><nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Philip Stock Tracker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
         <a class="nav-link" href="{% url 'logout'%}">Logout</a>
        </p>
      </div>
    </div>
  </div>
</nav></p>
    {% endif %}
  {% endfor %}
{% endif %}
          <div style="background-image: linear-gradient(to right top, #ffffff, #eeedfa, #dadcf5, #c5cbf1, #acbced, #9bbdf2, #85bef6, #69bff8, #52cffe, #41dfff, #46eefa, #5ffbf1);">
              <div style = "background-size: cover">
  <main>
    <h1>{% block header %} {% endblock %}</h1>

    {% block content %}

    {% endblock %}
  </main>
          </div>
          </div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.3.2/chart.min.js" integrity="sha512-VCHVc5miKoln972iJPvkQrUYYq7XpxXzvqNfiul1H4aZDwGBGC0lq373KNleaB2LpnC2a/iNfE5zoRYmB4TRDQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</body>
</html>
{# This is the parent view that can be inherited by any other views #}
{# Todo: Add navbar links, link to stylesheets, style layout #}

trash_collector/templates/home.html
{% extends 'base.html' %}

{% block title %}Home Portal{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hello {{ user.username }}. You don't have a group assigned. Please contact administrator or attempt to register again.
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in. Please log in or create an account.</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'accounts:register' %}">Sign Up</a>
{% endif %}
{% endblock %}

{# This is the home page that allows a logged out user to register or log in #}