trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/positions/urls.py
from django.urls import path

from . import views

app_name = 'positions'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.create, name='add_stock'),
    path('update_all/', views.update_all, name='update_all'),
    path('edit/<int:position_id>/', views.edit, name='edit')

]

trash_collector/positions/models.py
from django.db import models


# Create your models here.
class Position(models.Model):
    user = models.ForeignKey('accounts.User', default=0, on_delete=models.CASCADE)
    selected_ticker = models.CharField(max_length=5, null=True)
    selected_value = models.IntegerField(default=0)
    position_value = models.IntegerField(default=0, null=True)
    stock_close_value = models.IntegerField(default=0,null=True)


    def __str__(self):
        return self.selected_ticker

trash_collector/positions/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import requests
from django.apps import apps
from .models import Position

# Create your views here.
headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Token faadb088abbd151884296572be6b19d0321922b3'
}


def index(request):
    return render(request, 'positions/index.html')


def edit(request, position_id):
    if request.method == 'POST':
        position = Position.objects.get(pk=position_id)
        user = request.user
        selected_ticker = position.selected_ticker
        selected_value = request.POST.get('selected_value')
        price_json = requests.get(f'https://api.tiingo.com/tiingo/daily/{selected_ticker}/prices',
                                  headers=headers)
        stock_info = price_json.json()
        close_value = stock_info[0]['close']
        stock_close_value = close_value
        selected_value_int = int(selected_value)
        position_value = stock_close_value * selected_value_int
        position = Position(pk=position.id, selected_value=selected_value,
                            stock_close_value=stock_close_value,
                            position_value=position_value, selected_ticker=selected_ticker, user_id=user.id)
        position.save()
        return HttpResponseRedirect(reverse('positions:index'))
    else:
        return render(request, 'positions/edit.html')


def create(request):
    if request.method == 'POST':
        user = request.user
        selected_ticker = request.POST.get('selected_ticker')
        selected_value = request.POST.get('selected_value')
        price_json = requests.get(f'https://api.tiingo.com/tiingo/daily/{selected_ticker}/prices',
                                  headers=headers)
        stock_info = price_json.json()
        close_value = stock_info[0]['close']
        stock_close_value = close_value
        selected_value_int = int(selected_value)
        position_value = stock_close_value * selected_value_int
        print(position_value)
        new_position = Position(selected_ticker=selected_ticker, selected_value=selected_value,
                                stock_close_value=stock_close_value, user_id=user.id, position_value=position_value)
        new_position.save()
        return HttpResponseRedirect(reverse('positions:index'))
    else:
        print('error')
        return HttpResponseRedirect(reverse('positions:index'))


def update_all(request):
    if request.method == 'POST':
        print("this works")
        user = request.user
        positions = Position.objects.all()
        for position in positions:
            if user.id == position.user_id:
                selected_ticker = position.selected_ticker
                selected_value = position.selected_value
                price_json = requests.get(f'https://api.tiingo.com/tiingo/daily/{selected_ticker}/prices',
                                          headers=headers)
                stock_info = price_json.json()
                close_value = stock_info[0]['close']
                stock_close_value = close_value
                selected_ticker = position.selected_ticker
                selected_value_int = int(selected_value)
                position_value = stock_close_value * selected_value_int
                position = Position(pk=position.id, selected_value=selected_value,
                                    stock_close_value=stock_close_value,
                                    position_value=position_value, selected_ticker=selected_ticker, user_id=user.id)
                position.save()
        return HttpResponseRedirect(reverse('positions:index'))

trash_collector/positions/templates/positions/add.html
 {% extends 'base.html' %}

{% block title %}{% block header %} Position Index{% endblock %}{% endblock %}
 {% block content %}
 {% if user.is_authenticated %}
    Hello Customer {{ user.username }}!
<form>
 {% csrf_token %}
 Stock Ticker:<input type="text" name="selected_ticker" id="selected_ticker"><br>
 Share Number:<input type="number" name="selected_value" id="selected_value">
 <input type="submit" value="Add Stock to Portfolio">
</form>



  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/positions/templates/positions/edit.html
 {% extends 'base.html' %}

{% block title %}{% block header %} Position Index{% endblock %}{% endblock %}
 {% block content %}
 {% if user.is_authenticated %}
    Hello Customer {{ user.username }}!
<form method="post">
 {% csrf_token %}
 Share Number:<input type="number" name="selected_value" id="selected_value">
 <input type="submit" value="Edit Stock Share Number">
</form>



  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/positions/templates/positions/index.html
 {% extends 'base.html' %}

{% block title %}{% block header %} Position Index{% endblock %}{% endblock %}
 {% block content %}
 {% if user.is_authenticated %}
    Hello Customer {{ user.username }}!
 <h1>Add a Stock to Portfolio</h1>
 <form action="{% url 'positions:add_stock' %}" method="post">
 {% csrf_token %}
 Stock Ticker:<input type="text" name="selected_ticker" id="selected_ticker"><br>
 Share Number:<input type="number" name="selected_value" id="selected_value"><br>
 <input type="submit" value="Add Stock to Portfolio">
</form>



  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/positions/templates/positions/update_all.html
 {% extends 'base.html' %}

{% block title %}{% block header %} Update Positions {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}

<h2>Your stocks have been updated!</h2>
  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}