trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path

from . import views

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('stocks/', views.apicall, name="stock"),
    path('add', views.apicall, name='add'),
    path('stock_details/<int:position_id>/', views.stock_details, name='stock_details'),
]

trash_collector/positions/urls.py
from django.urls import path

from . import views

app_name = 'positions'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.create, name='add_stock'),
    path('update_all/', views.update_all, name='update_all'),
    path('edit/<int:position_id>/', views.edit, name='edit')

]

trash_collector/customers/models.py
from django.db import models


# Create your models here.

class Customer(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', default=0, on_delete=models.CASCADE)

trash_collector/customers/views.py
from os.path import join

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Customer
import requests
from django.apps import apps
import datetime

import json


headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Token faadb088abbd151884296572be6b19d0321922b3'
}


def index(request):
    user = request.user
    Position = apps.get_model('positions.Position')
    positions = Position.objects.all()
    selected_positions = []
    portfolio_balance = 0
    for position in positions:
        if user.id == position.user_id:
            portfolio_balance += position.position_value
            selected_positions.append(position)

    return render(request, 'customers/index.html',
                  {'selected_positions': selected_positions, 'portfolio_balance': portfolio_balance})


def stock(request):
    return render(request, 'customers/stock.html')


def apicall(request):
    position = request.GET['ticker']
    today = datetime.date.today()
    five_delta = datetime.timedelta(-10)
    early_day = today + five_delta
    stock_news = requests.get(f'https://api.tiingo.com/tiingo/news?tickers={position}',
                              headers=headers)
    stock_news_json = stock_news.json()
    stock_news_one = stock_news_json[0]['description']
    stock_url_one = stock_news_json[0]['url']
    stock_news_two = stock_news_json[1]['description']
    stock_url_two = stock_news_json[1]['url']
    stock_news_three = stock_news_json[2]['description']
    stock_url_three = stock_news_json[2]['url']
    stock_news_four = stock_news_json[3]['description']
    stock_url_four = stock_news_json[3]['url']
    stock_news_five = stock_news_json[4]['description']
    stock_url_five = stock_news_json[4]['url']

    price_json = requests.get(f'https://api.tiingo.com/tiingo/daily/{position}/prices',
                              headers=headers)
    stock_info = price_json.json()

    meta_json = requests.get(f'https://api.tiingo.com/tiingo/daily/{position}',
                             headers=headers)
    stock_meta = meta_json.json()
    stock_name = stock_meta['name']
    stock_description = stock_meta['description']
    close_value = stock_info[0]['close']
    high_value = stock_info[0]['high']
    low_value = stock_info[0]['low']
    volume = stock_info[0]['volume']
    historical_data = requests.get(
        f'https://api.tiingo.com/tiingo/daily/{position}/prices?startDate={early_day}&endDate={today}&format=json&resampleFreq=daily',
        headers=headers)
    historical_data_json = historical_data.json()
    active_dates = []

    for i in range(len(historical_data_json)):
        date_time = datetime.datetime.strptime(historical_data_json[i]['date'], "%Y-%m-%dT%H:%M:%S.%fZ")
        date_time_list = date_time.strftime("%B %d")
        active_dates.append(date_time_list)

    historical_prices = []
    historical_dates = []
    for i in range(len(historical_data_json)):
        historical_prices.append(historical_data_json[i]['close'])
        historical_dates.append(historical_data_json[i]['date'])

    return render(request, 'customers/stock_details.html',
                  {'position': position, 'historical_data_json': historical_data_json,
                   'historical_prices': historical_prices, 'historical_dates': historical_dates,
                   'active_dates': active_dates, 'close_value': close_value, 'high_value': high_value,
                   'low_value': low_value, 'volume': volume, 'stock_name': stock_name,
                   'stock_description': stock_description, 'stock_news_json': stock_news_json,
                   'stock_news_one': stock_news_one, 'stock_url_one': stock_url_one, 'stock_news_two': stock_news_two,
                   'stock_url_two': stock_url_two, 'stock_news_three': stock_news_three,
                   'stock_url_three': stock_url_three, 'stock_news_four': stock_news_four,
                   'stock_url_four': stock_url_four, 'stock_news_five': stock_news_five,
                   'stock_url_five': stock_url_five})


def stock_details(request, position_id):
    Position = apps.get_model('positions.Position')
    position = Position.objects.get(pk=position_id)
    today = datetime.date.today()
    five_delta = datetime.timedelta(-10)
    early_day = today + five_delta
    stock_news = requests.get(f'https://api.tiingo.com/tiingo/news?tickers={position}',
                              headers=headers)
    stock_news_json = stock_news.json()
    stock_news_one = stock_news_json[0]['description']
    stock_url_one = stock_news_json[0]['url']
    stock_news_two = stock_news_json[1]['description']
    stock_url_two = stock_news_json[1]['url']
    stock_news_three = stock_news_json[2]['description']
    stock_url_three = stock_news_json[2]['url']
    stock_news_four = stock_news_json[3]['description']
    stock_url_four = stock_news_json[3]['url']
    stock_news_five = stock_news_json[4]['description']
    stock_url_five = stock_news_json[4]['url']

    price_json = requests.get(f'https://api.tiingo.com/tiingo/daily/{position}/prices',
                              headers=headers)
    stock_info = price_json.json()

    meta_json = requests.get(f'https://api.tiingo.com/tiingo/daily/{position}',
                             headers=headers)
    stock_meta = meta_json.json()
    stock_name = stock_meta['name']
    stock_description = stock_meta['description']
    close_value = stock_info[0]['close']
    high_value = stock_info[0]['high']
    low_value = stock_info[0]['low']
    volume = stock_info[0]['volume']
    historical_data = requests.get(
        f'https://api.tiingo.com/tiingo/daily/{position}/prices?startDate={early_day}&endDate={today}&format=json&resampleFreq=daily',
        headers=headers)
    historical_data_json = historical_data.json()
    active_dates = []

    for i in range(len(historical_data_json)):
        date_time = datetime.datetime.strptime(historical_data_json[i]['date'], "%Y-%m-%dT%H:%M:%S.%fZ")
        date_time_list = date_time.strftime("%B %d")
        active_dates.append(date_time_list)

    historical_prices = []
    historical_dates = []
    for i in range(len(historical_data_json)):
        historical_prices.append(historical_data_json[i]['close'])
        historical_dates.append(historical_data_json[i]['date'])

    return render(request, 'customers/stock_details.html',
                  {'position': position, 'historical_data_json': historical_data_json,
                   'historical_prices': historical_prices, 'historical_dates': historical_dates,
                   'active_dates': active_dates, 'close_value': close_value, 'high_value': high_value,
                   'low_value': low_value, 'volume': volume, 'stock_name': stock_name,
                   'stock_description': stock_description, 'stock_news_json': stock_news_json,
                   'stock_news_one': stock_news_one, 'stock_url_one': stock_url_one, 'stock_news_two': stock_news_two,
                   'stock_url_two': stock_url_two, 'stock_news_three': stock_news_three,
                   'stock_url_three': stock_url_three, 'stock_news_four': stock_news_four,
                   'stock_url_four': stock_url_four, 'stock_news_five': stock_news_five,
                   'stock_url_five': stock_url_five})

trash_collector/customers/templates/customers/index.html
 {% extends 'base.html' %}

{% block title %} Your Stock Positions {% endblock %}

{% block content %}
  {% if user.is_authenticated %}

<div class="container">
    <div class="row">

        <div class="col">
 <h3>The total value of {{user.username}}'s portfolio is:  ${{portfolio_balance}}</h3>
        </div>
    <div class="col-sm-4">
<form action="{% url 'positions:update_all' %}" method="POST">
    {% csrf_token %}

    <input type="submit" value ="Get Updated Prices">

    </form>
        </div>
    </div>


<div class="row">

 <table class ="table">
  <thead>
  <th scope="col">Stock Ticker</th>
  <th scope="col">Number of Shares</th>
  <th scope="col"> Stock Value</th>
  <th scope="col"> Position Value</th>
  <th scope="col">View Details </th>
  <th scope="col"> Edit Share Number</th>

  </thead>
<tbody>
 {% for selected_position in selected_positions %}
<tr><td>
{{selected_position.selected_ticker}}
</td>

 <td>
 {{selected_position.selected_value}}
 </td>
    <td>
        ${{selected_position.stock_close_value}}
    </td>
    <td>
        ${{selected_position.position_value}}
    </td>
    <td>
        <button type = "button"> <a href="{% url 'customers:stock_details' selected_position.id %}">View Details</a></button>
    </td>
        <td>
            <button type="button"> <a href="{% url 'positions:edit' selected_position.id %}">Edit</a></button>
    </td>
{% endfor %}


</tr>

  </tbody>
</table>
 <br>
    </div>
    <div class="row">
        <h3>Search for a stock!</h3>
                 <form action="add">
  Enter Stock Ticker: <input type="text" name="ticker">
  <input type="submit">
        </form>

    </div>
</div>
  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/customers/templates/customers/render_stock.html
Render Page

trash_collector/customers/templates/customers/stock.html
 {% extends 'base.html' %}

 {% block title %}{% block header %}{{position}} Stock Details {% endblock %}{% endblock %}
 {% block scripts %}
 <script>
   $(document).ready(function(){
    var ctx = document.getElementById('myChart');
    var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: [{% for active_date in active_dates %}'{{active_date}}',{% endfor %}],
        datasets: [{
            label: ' Stock: {{position}} ',
            data: [{% for historical_price in historical_prices %}'{{historical_price}}',{% endfor %}],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: false
            }
        }
    }
});
   })
 </script>
 {% endblock scripts %}
 {% block content %}
 {% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col">

 Stock Name: {{stock_name}}<br>
 Highest Price(last 24):{{high_value}}<br>
 Lowest Price (last 24):{{low_value}}<br>
 Volume: {{volume}}<br>
 Closing value:{{close_value}}<br>
        </div>
        <div class="col-8">
            Stock Description: {{stock_description}}<br>
        </div>
    </div>
    <div class="row">
 <canvas id="myChart" width="200" height="60"></canvas>
    </div>

      <div class="row">
          <center><h3>Relevant News</h3></center>
{{stock_news_one}}<br>
 <a href={{stock_url_one}}>{{stock_url_one}}</a><br>
 {{stock_news_two}}<br>
 <a href={{stock_url_two}}>{{stock_url_two}}</a><br>
 {{stock_news_three}}<br>
 <a href={{stock_url_three}}>{{stock_url_three}}</a><br>
 {{stock_news_four}}<br>
 <a href={{stock_url_four}}>{{stock_url_four}}</a><br>
 {{stock_news_five}}<br>
 <a href={{stock_url_five}}>{{stock_url_five}}</a><br>
    </div>
</div>

 {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/customers/templates/customers/stock_details.html
 {% extends 'base.html' %}

 {% block title %}{% block header %}{{position}} Stock Details {% endblock %}{% endblock %}
 {% block scripts %}
 <script>
   $(document).ready(function(){
    var ctx = document.getElementById('myChart');
    var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: [{% for active_date in active_dates %}'{{active_date}}',{% endfor %}],
        datasets: [{
            label: ' Stock: {{position}} ',
            data: [{% for historical_price in historical_prices %}'{{historical_price}}',{% endfor %}],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: false
            }
        }
    }
});
   })
 </script>
 {% endblock scripts %}
 {% block content %}
 {% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col">

 Stock Name: {{stock_name}}<br>
 Highest Price(last 24):{{high_value}}<br>
 Lowest Price (last 24):{{low_value}}<br>
 Volume: {{volume}}<br>
 Closing value:{{close_value}}<br>
        </div>
        <div class="col-8">
            Stock Description: {{stock_description}}<br>
        </div>
    </div>
    <div class="row">
 <canvas id="myChart" width="200" height="60"></canvas>
    </div>

      <div class="row">
          <center><h3>Relevant News</h3></center>
{{stock_news_one}}<br>
 <a href={{stock_url_one}}>{{stock_url_one}}</a><br>
 {{stock_news_two}}<br>
 <a href={{stock_url_two}}>{{stock_url_two}}</a><br>
 {{stock_news_three}}<br>
 <a href={{stock_url_three}}>{{stock_url_three}}</a><br>
 {{stock_news_four}}<br>
 <a href={{stock_url_four}}>{{stock_url_four}}</a><br>
 {{stock_news_five}}<br>
 <a href={{stock_url_five}}>{{stock_url_five}}</a><br>
    </div>
</div>

 {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}